In [1]:
import pandas as pd

In [2]:
file_path = r"C:\Users\lavan\Downloads\globalterrorismdb_0718dist.csv"

df = pd.read_csv(file_path, low_memory=False)

In [3]:
df.shape

(181691, 136)

In [4]:
df.columns.tolist()

['Unnamed: 0',
 'eventid',
 'iyear',
 'imonth',
 'iday',
 'approxdate',
 'extended',
 'resolution',
 'country',
 'country_txt',
 'region',
 'region_txt',
 'provstate',
 'city',
 'latitude',
 'longitude',
 'specificity',
 'vicinity',
 'location',
 'summary',
 'crit1',
 'crit2',
 'crit3',
 'doubtterr',
 'alternative',
 'alternative_txt',
 'multiple',
 'success',
 'suicide',
 'attacktype1',
 'attacktype1_txt',
 'attacktype2',
 'attacktype2_txt',
 'attacktype3',
 'attacktype3_txt',
 'targtype1',
 'targtype1_txt',
 'targsubtype1',
 'targsubtype1_txt',
 'corp1',
 'target1',
 'natlty1',
 'natlty1_txt',
 'targtype2',
 'targtype2_txt',
 'targsubtype2',
 'targsubtype2_txt',
 'corp2',
 'target2',
 'natlty2',
 'natlty2_txt',
 'targtype3',
 'targtype3_txt',
 'targsubtype3',
 'targsubtype3_txt',
 'corp3',
 'target3',
 'natlty3',
 'natlty3_txt',
 'gname',
 'gsubname',
 'gname2',
 'gsubname2',
 'gname3',
 'gsubname3',
 'motive',
 'guncertain1',
 'guncertain2',
 'guncertain3',
 'individual',
 'nperps',
 'nperpcap',
 'claimed',
 'claimmode',
 'claimmode_txt',
 'claim2',
 'claimmode2',
 'claimmode2_txt',
 'claim3',
 'claimmode3',
 'claimmode3_txt',
 'compclaim',
 'weaptype1',
 'weaptype1_txt',
 'weapsubtype1',
 'weapsubtype1_txt',
 'weaptype2',
 'weaptype2_txt',
 'weapsubtype2',
 'weapsubtype2_txt',
 'weaptype3',
 'weaptype3_txt',
 'weapsubtype3',
 'weapsubtype3_txt',
 'weaptype4',
 'weaptype4_txt',
 'weapsubtype4',
 'weapsubtype4_txt',
 'weapdetail',
 'nkill',
 'nkillus',
 'nkillter',
 'nwound',
 'nwoundus',
 'nwoundte',
 'property',
 'propextent',
 'propextent_txt',
 'propvalue',
 'propcomment',
 'ishostkid',
 'nhostkid',
 'nhostkidus',
 'nhours',
 'ndays',
 'divert',
 'kidhijcountry',
 'ransom',
 'ransomamt',
 'ransomamtus',
 'ransompaid',
 'ransompaidus',
 'ransomnote',
 'hostkidoutcome',
 'hostkidoutcome_txt',
 'nreleased',
 'addnotes',
 'scite1',
 'scite2',
 'scite3',
 'dbsource',
 'INT_LOG',
 'INT_IDEO',
 'INT_MISC',
 'INT_ANY',
 'related']

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Columns: 136 entries, Unnamed: 0 to related
dtypes: float64(55), int64(23), object(58)
memory usage: 188.5+ MB

In [6]:
missing = pd.DataFrame({
    'column': df.columns,
    'missing_count': df.isna().sum(),
    'missing_pct': (df.isna().mean() * 100).round(2)
})

missing.sort_values('missing_pct', ascending=False).head(30)

                            column  missing_count  missing_pct
gsubname3                gsubname3         181671        99.99
weaptype4                weaptype4         181618        99.96
weaptype4_txt        weaptype4_txt         181618        99.96
weapsubtype4          weapsubtype4         181621        99.96
weapsubtype4_txt  weapsubtype4_txt         181621        99.96
claimmode3              claimmode3         181558        99.93
claimmode3_txt      claimmode3_txt         181558        99.93
gsubname2                gsubname2         181531        99.91
guncertain3            guncertain3         181371        99.82
divert                      divert         181367        99.82
claim3                      claim3         181373        99.82
gname3                      gname3         181367        99.82
attacktype3_txt    attacktype3_txt         181263        99.76
attacktype3            attacktype3         181263        99.76
ransomnote              ransomnote         181179        99.72
ransompaidus          ransompaidus         181139        99.70
ransomamtus            ransomamtus         181128        99.69
claimmode2_txt      claimmode2_txt         181075        99.66
claimmode2              claimmode2         181075        99.66
ransompaid              ransompaid         180917        99.57
corp3                        corp3         180665        99.44
targsubtype3          targsubtype3         180594        99.40
targsubtype3_txt  targsubtype3_txt         180594        99.40
natlty3                    natlty3         180544        99.37
natlty3_txt            natlty3_txt         180544        99.37
target3                    target3         180516        99.35
targtype3_txt        targtype3_txt         180515        99.35
targtype3                targtype3         180515        99.35
ransomamt                ransomamt         180341        99.26
weapsubtype3          weapsubtype3         179998        99.07

In [7]:
dashboard_cols = [
    'eventid',
    'iyear',
    'imonth',
    'iday',
    'country',
    'country_txt',
    'region',
    'region_txt',
    'provstate',
    'city',
    'latitude',
    'longitude',
    'success',
    'suicide',
    'attacktype1',
    'attacktype1_txt',
    'targtype1',
    'targtype1_txt',
    'weaptype1',
    'weaptype1_txt',
    'gname',
    'nperps',
    'nkill',
    'nkillus',
    'nwound'
]

profile = pd.DataFrame({
    'data_type': df[dashboard_cols].dtypes,
    'missing_count': df[dashboard_cols].isna().sum(),
    'missing_pct': (df[dashboard_cols].isna().mean() * 100).round(2),
    'unique_values': df[dashboard_cols].nunique()
})

profile

                data_type  missing_count  missing_pct  unique_values
eventid             int64              0         0.00         181691
iyear               int64              0         0.00             47
imonth              int64              0         0.00             13
iday                int64              0         0.00             32
country             int64              0         0.00            205
country_txt        object              0         0.00            205
region              int64              0         0.00             12
region_txt         object              0         0.00             12
provstate          object            421         0.23           2854
city               object            435         0.24          36673
latitude          float64           4556         2.51          48322
longitude         float64           4557         2.51          48039
success             int64              0         0.00              2
suicide             int64              0         0.00              2
attacktype1         int64              0         0.00              9
attacktype1_txt    object              0         0.00              9
targtype1           int64              0         0.00             22
targtype1_txt      object              0         0.00             22
weaptype1           int64              0         0.00             12
weaptype1_txt      object              0         0.00             12
gname              object              0         0.00           3537
nperps            float64          71115        39.14            113
nkill             float64          10313         5.68            205
nkillus           float64          64446        35.47             31
nwound            float64          16311         8.98            238

In [8]:
dashboard_cols

['eventid',
 'iyear',
 'imonth',
 'iday',
 'country',
 'country_txt',
 'region',
 'region_txt',
 'provstate',
 'city',
 'latitude',
 'longitude',
 'success',
 'suicide',
 'attacktype1',
 'attacktype1_txt',
 'targtype1',
 'targtype1_txt',
 'weaptype1',
 'weaptype1_txt',
 'gname',
 'nperps',
 'nkill',
 'nkillus',
 'nwound']

In [9]:
profile

                data_type  missing_count  missing_pct  unique_values
eventid             int64              0         0.00         181691
iyear               int64              0         0.00             47
imonth              int64              0         0.00             13
iday                int64              0         0.00             32
country             int64              0         0.00            205
country_txt        object              0         0.00            205
region              int64              0         0.00             12
region_txt         object              0         0.00             12
provstate          object            421         0.23           2854
city               object            435         0.24          36673
latitude          float64           4556         2.51          48322
longitude         float64           4557         2.51          48039
success             int64              0         0.00              2
suicide             int64              0         0.00              2
attacktype1         int64              0         0.00              9
attacktype1_txt    object              0         0.00              9
targtype1           int64              0         0.00             22
targtype1_txt      object              0         0.00             22
weaptype1           int64              0         0.00             12
weaptype1_txt      object              0         0.00             12
gname              object              0         0.00           3537
nperps            float64          71115        39.14            113
nkill             float64          10313         5.68            205
nkillus           float64          64446        35.47             31
nwound            float64          16311         8.98            238

In [10]:
for col in [
    'success',
    'suicide',
    'attacktype1_txt',
    'targtype1_txt',
    'weaptype1_txt'
]:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(15))

--- success ---
success
1    161632
0     20059
Name: count, dtype: int64

--- suicide ---
suicide
0    175058
1      6633
Name: count, dtype: int64

--- attacktype1_txt ---
attacktype1_txt
Bombing/Explosion                      88255
Armed Assault                          42669
Assassination                          19312
Hostage Taking (Kidnapping)            11158
Facility/Infrastructure Attack         10356
Unknown                                 7276
Unarmed Assault                         1015
Hostage Taking (Barricade Incident)      991
Hijacking                                659
Name: count, dtype: int64

--- targtype1_txt ---
targtype1_txt
Private Citizens & Property       43511
Military                          27984
Police                            24506
Government (General)              21283
Business                          20669
Transportation                     6799
Utilities                          6023
Unknown                            5898
Religious Figures/Institutions     4440
Educational Institution            4322
Government (Diplomatic)            3573
Terrorists/Non-State Militia       3039
Journalists & Media                2948
Violent Political Party            1866
Airports & Aircraft                1343
Name: count, dtype: int64

--- weaptype1_txt ---
weaptype1_txt
Explosives                                                                     92426
Firearms                                                                       58524
Unknown                                                                        15157
Incendiary                                                                     11135
Melee                                                                           3655
Chemical                                                                         321
Sabotage Equipment                                                               141
Vehicle (not to include vehicle-borne explosives, i.e., car or truck bombs)      136
Other                                                                            114
Biological                                                                        35
Fake Weapons                                                                      33
Radiological                                                                      14
Name: count, dtype: int64

In [11]:
analysis_cols = [
    'eventid',
    'iyear',
    'imonth',
    'iday',
    'country',
    'country_txt',
    'region',
    'region_txt',
    'provstate',
    'city',
    'latitude',
    'longitude',
    'success',
    'suicide',
    'attacktype1',
    'attacktype1_txt',
    'targtype1',
    'targtype1_txt',
    'weaptype1',
    'weaptype1_txt',
    'gname',
    'nkill',
    'nwound'
]

df_analysis = df[analysis_cols].copy()

df_analysis.shape

(181691, 23)

In [12]:
df_analysis.head()

,eventid,iyear,imonth,iday,country,country_txt,region,region_txt,provstate,city,...,suicide,attacktype1,attacktype1_txt,targtype1,targtype1_txt,weaptype1,weaptype1_txt,gname,nkill,nwound
0,197000000001,1970,7,2,58,Dominican Republic,2,Central America & Caribbean,NaN,Santo Domingo,...,0,1,Assassination,14,Private Citizens & Property,13,Unknown,MANO-D,1.0,0.0
1,197000000002,1970,0,0,130,Mexico,1,North America,Federal,Mexico city,...,0,6,Hostage Taking (Kidnapping),7,Government (Diplomatic),13,Unknown,23rd of September Communist League,0.0,0.0
2,197001000001,1970,1,0,160,Philippines,5,Southeast Asia,Tarlac,Unknown,...,0,1,Assassination,10,Journalists & Media,13,Unknown,Unknown,1.0,0.0
3,197001000002,1970,1,0,78,Greece,8,Western Europe,Attica,Athens,...,0,3,Bombing/Explosion,7,Government (Diplomatic),6,Explosives,Unknown,NaN,NaN
4,197001000003,1970,1,0,101,Japan,4,East Asia,Fukouka,Fukouka,...,0,7,Facility/Infrastructure Attack,7,Government (Diplomatic),8,Incendiary,Unknown,NaN,NaN

In [13]:
output_path = r"C:\Users\lavan\Downloads\GTD_dashboard.csv"

df_analysis.to_csv(output_path, index=False)

print("Saved successfully:", output_path)

Saved successfully: C:\Users\lavan\Downloads\GTD_dashboard.csv

In [14]:
df_analysis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Data columns (total 23 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   eventid          181691 non-null  int64
 1   iyear            181691 non-null  int64
 2   imonth           181691 non-null  int64
 3   iday             181691 non-null  int64
 4   country          181691 non-null  int64
 5   country_txt      181691 non-null  object
 6   region           181691 non-null  int64
 7   region_txt       181691 non-null  object
 8   provstate        181270 non-null  object
 9   city             181256 non-null  object
 10  latitude         177135 non-null  float64
 11  longitude        177134 non-null  float64
 12  success          181691 non-null  int64
 13  suicide          181691 non-null  int64
 14  attacktype1      181691 non-null  int64
 15  attacktype1_txt  181691 non-null  object
 16  targtype1        181691 non-null  int64
 17  targtype1_txt    181691 non-null  object
 18  weaptype1        181691 non-null  int64
 19  weaptype1_txt    181691 non-null  object
 20  gname            181691 non-null  object
 21  nkill            171378 non-null  float64
 22  nwound           165380 non-null  float64
dtypes: float64(4), int64(11), object(8)
memory usage: 31.9+ MB

In [15]:
import sqlalchemy
print(sqlalchemy.__version__)

2.0.43

In [16]:
from sqlalchemy import create_engine

server = "localhost"
database = "GlobalTerrorism"

connection_string = (
    "mssql+pyodbc://@"
    + server
    + "/"
    + database
    + "?driver=ODBC+Driver+17+for+SQL+Server"
    + "&trusted_connection=yes"
)

engine = create_engine(connection_string)

print("Connection created successfully")

Connection created successfully

In [17]:
from sqlalchemy import inspect

inspector = inspect(engine)

tables = inspector.get_table_names()

tables

C:\Users\lavan\AppData\Local\Temp\ipykernel_41332\3217550688.py:3: SAWarning: Unrecognized server version info '17.0.1125.2'.  Some SQL Server features may not function properly.
  inspector = inspect(engine)

[]

In [18]:
df_analysis.to_sql(
    "GTD_Dashboard",
    engine,
    if_exists="replace",
    index=False,
    chunksize=5000
)

print("GTD_Dashboard table created successfully")

GTD_Dashboard table created successfully